package net.biker.wallsnstuff.item;

import net.biker.wallsnstuff.Wallsnstuff;
import net.biker.wallsnstuff.block.ModBlocks;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;


public class ModItemGroups {
    public static final ItemGroup WALLS_GROUP = Registry.register(Registries.ITEM_GROUP,
            new Identifier(Wallsnstuff.MOD_ID, "walls"),
            FabricItemGroup.builder().displayName(Text.translatable("itemgroup.walls"))
                    .icon(() -> new ItemStack(ModBlocks.COBBLESTONE_FENCE)).entries((displayContext, entries) -> {

                        entries.add(ModBlocks.COBBLESTONE_FENCE);
                        entries.add(ModBlocks.COBBLESTONE_FENCE_GATE);
                        entries.add(ModBlocks.DIRT_FENCE_GATE);
                        entries.add(ModBlocks.DIRT_FENCE);
                        entries.add(ModBlocks.DIRT_WALL);
                        entries.add(ModBlocks.ICE_WALL);
                        entries.add(ModBlocks.ICE_FENCE);
                        entries.add(ModBlocks.ICE_FENCE_GATE);
                        entries.add(ModBlocks.OAK_LOG_WALL);
                        entries.add(ModBlocks.OAK_LOG_FENCE);
                        entries.add(ModBlocks.OAK_LOG_FENCE_GATE);
                        entries.add(ModBlocks.COPPER_BLOCK_FENCE);
                        entries.add(ModBlocks.COPPER_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.COPPER_BLOCK_WALL);
                        entries.add(ModBlocks.EXPOSED_COPPER_FENCE);
                        entries.add(ModBlocks.EXPOSED_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.EXPOSED_COPPER_WALL);
                        entries.add(ModBlocks.WEATHERED_COPPER_FENCE);
                        entries.add(ModBlocks.WEATHERED_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.WEATHERED_COPPER_WALL);
                        entries.add(ModBlocks.OXIDIZED_COPPER_FENCE);
                        entries.add(ModBlocks.OXIDIZED_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.OXIDIZED_COPPER_WALL);
                        entries.add(ModBlocks.CUT_COPPER_FENCE);
                        entries.add(ModBlocks.CUT_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.CUT_COPPER_WALL);
                        entries.add(ModBlocks.EXPOSED_CUT_COPPER_FENCE);
                        entries.add(ModBlocks.EXPOSED_CUT_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.EXPOSED_CUT_COPPER_WALL);
                        entries.add(ModBlocks.WEATHERED_CUT_COPPER_FENCE);
                        entries.add(ModBlocks.WEATHERED_CUT_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.WEATHERED_CUT_COPPER_WALL);
                        entries.add(ModBlocks.OXIDIZED_CUT_COPPER_FENCE);
                        entries.add(ModBlocks.OXIDIZED_CUT_COPPER_FENCE_GATE);
                        entries.add(ModBlocks.OXIDIZED_CUT_COPPER_WALL);
                        entries.add(ModBlocks.WHITE_WOOL_FENCE);
                        entries.add(ModBlocks.WHITE_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.WHITE_WOOL_WALL);
                        entries.add(ModBlocks.ORANGE_WOOL_FENCE);
                        entries.add(ModBlocks.ORANGE_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.ORANGE_WOOL_WALL);
                        entries.add(ModBlocks.MAGENTA_WOOL_FENCE);
                        entries.add(ModBlocks.MAGENTA_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.MAGENTA_WOOL_WALL);
                        entries.add(ModBlocks.LIGHT_BLUE_WOOL_FENCE);
                        entries.add(ModBlocks.LIGHT_BLUE_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_BLUE_WOOL_WALL);
                        entries.add(ModBlocks.YELLOW_WOOL_FENCE);
                        entries.add(ModBlocks.YELLOW_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.YELLOW_WOOL_WALL);
                        entries.add(ModBlocks.LIME_WOOL_FENCE);
                        entries.add(ModBlocks.LIME_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.LIME_WOOL_WALL);
                        entries.add(ModBlocks.PINK_WOOL_FENCE);
                        entries.add(ModBlocks.PINK_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.PINK_WOOL_WALL);
                        entries.add(ModBlocks.GRAY_WOOL_FENCE);
                        entries.add(ModBlocks.GRAY_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.GRAY_WOOL_WALL);
                        entries.add(ModBlocks.LIGHT_GRAY_WOOL_FENCE);
                        entries.add(ModBlocks.LIGHT_GRAY_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_GRAY_WOOL_WALL);
                        entries.add(ModBlocks.CYAN_WOOL_FENCE);
                        entries.add(ModBlocks.CYAN_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.CYAN_WOOL_WALL);
                        entries.add(ModBlocks.PURPLE_WOOL_FENCE);
                        entries.add(ModBlocks.PURPLE_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.PURPLE_WOOL_WALL);
                        entries.add(ModBlocks.BLUE_WOOL_FENCE);
                        entries.add(ModBlocks.BLUE_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.BLUE_WOOL_WALL);
                        entries.add(ModBlocks.BROWN_WOOL_FENCE);
                        entries.add(ModBlocks.BROWN_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.BROWN_WOOL_WALL);
                        entries.add(ModBlocks.GREEN_WOOL_FENCE);
                        entries.add(ModBlocks.GREEN_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.GREEN_WOOL_WALL);
                        entries.add(ModBlocks.RED_WOOL_FENCE);
                        entries.add(ModBlocks.RED_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.RED_WOOL_WALL);
                        entries.add(ModBlocks.BLACK_WOOL_FENCE);
                        entries.add(ModBlocks.BLACK_WOOL_FENCE_GATE);
                        entries.add(ModBlocks.BLACK_WOOL_WALL);
                        entries.add(ModBlocks.TERRACOTTA_FENCE);
                        entries.add(ModBlocks.TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.TERRACOTTA_WALL);
                        entries.add(ModBlocks.WHITE_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.WHITE_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.WHITE_TERRACOTTA_WALL);
                        entries.add(ModBlocks.ORANGE_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.ORANGE_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.ORANGE_TERRACOTTA_WALL);
                        entries.add(ModBlocks.MAGENTA_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.MAGENTA_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.MAGENTA_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIGHT_BLUE_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIGHT_BLUE_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_BLUE_TERRACOTTA_WALL);
                        entries.add(ModBlocks.YELLOW_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.YELLOW_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.YELLOW_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIME_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIME_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIME_TERRACOTTA_WALL);
                        entries.add(ModBlocks.PINK_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.PINK_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.PINK_TERRACOTTA_WALL);
                        entries.add(ModBlocks.GRAY_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.GRAY_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.GRAY_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIGHT_GRAY_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIGHT_GRAY_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_GRAY_TERRACOTTA_WALL);
                        entries.add(ModBlocks.CYAN_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.CYAN_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.CYAN_TERRACOTTA_WALL);
                        entries.add(ModBlocks.PURPLE_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.PURPLE_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.PURPLE_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BLUE_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BLUE_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BLUE_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BROWN_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BROWN_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BROWN_TERRACOTTA_WALL);
                        entries.add(ModBlocks.GREEN_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.GREEN_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.GREEN_TERRACOTTA_WALL);
                        entries.add(ModBlocks.RED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.RED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.RED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BLACK_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BLACK_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BLACK_TERRACOTTA_WALL);
                        entries.add(ModBlocks.WHITE_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.WHITE_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.WHITE_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.ORANGE_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.ORANGE_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.ORANGE_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.MAGENTA_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.YELLOW_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.YELLOW_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.YELLOW_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIME_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIME_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIME_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.PINK_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.PINK_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.PINK_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.GRAY_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.GRAY_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.GRAY_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.CYAN_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.CYAN_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.CYAN_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.PURPLE_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.PURPLE_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.PURPLE_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BLUE_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BLUE_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BLUE_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BROWN_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BROWN_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BROWN_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.GREEN_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.GREEN_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.GREEN_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.RED_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.RED_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.RED_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.BLACK_GLAZED_TERRACOTTA_FENCE);
                        entries.add(ModBlocks.BLACK_GLAZED_TERRACOTTA_FENCE_GATE);
                        entries.add(ModBlocks.BLACK_GLAZED_TERRACOTTA_WALL);
                        entries.add(ModBlocks.WHITE_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.WHITE_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.WHITE_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.ORANGE_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.ORANGE_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.ORANGE_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.MAGENTA_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.MAGENTA_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.MAGENTA_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.LIGHT_BLUE_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_BLUE_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.YELLOW_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.YELLOW_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.YELLOW_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.LIME_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.LIME_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.LIME_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.PINK_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.PINK_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.PINK_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.GRAY_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.GRAY_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.GRAY_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.LIGHT_GRAY_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.LIGHT_GRAY_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.CYAN_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.CYAN_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.CYAN_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.PURPLE_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.PURPLE_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.PURPLE_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.BLUE_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.BLUE_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.BLUE_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.BROWN_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.BROWN_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.BROWN_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.GREEN_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.GREEN_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.GREEN_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.RED_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.RED_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.RED_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.BLACK_STAINED_GLASS_FENCE);
                        entries.add(ModBlocks.BLACK_STAINED_GLASS_FENCE_GATE);
                        entries.add(ModBlocks.BLACK_STAINED_GLASS_WALL);
                        entries.add(ModBlocks.GRAVEL_FENCE);
                        entries.add(ModBlocks.GRAVEL_FENCE_GATE);
                        entries.add(ModBlocks.GRAVEL_WALL);
                        entries.add(ModBlocks.CLAY_FENCE);
                        entries.add(ModBlocks.CLAY_FENCE_GATE);
                        entries.add(ModBlocks.CLAY_WALL);
                        entries.add(ModBlocks.SAND_FENCE);
                        entries.add(ModBlocks.SAND_FENCE_GATE);
                        entries.add(ModBlocks.SAND_WALL);
                        entries.add(ModBlocks.RED_SAND_FENCE);
                        entries.add(ModBlocks.RED_SAND_FENCE_GATE);
                        entries.add(ModBlocks.RED_SAND_WALL);
                        entries.add(ModBlocks.PACKED_ICE_FENCE);
                        entries.add(ModBlocks.PACKED_ICE_FENCE_GATE);
                        entries.add(ModBlocks.PACKED_ICE_WALL);
                        entries.add(ModBlocks.BLUE_ICE_FENCE);
                        entries.add(ModBlocks.BLUE_ICE_FENCE_GATE);
                        entries.add(ModBlocks.BLUE_ICE_WALL);

                        entries.add(ModBlocks.MOSS_BLOCK_FENCE);
                        entries.add(ModBlocks.MOSS_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.MOSS_BLOCK_WALL);
                        entries.add(ModBlocks.CALCITE_FENCE);
                        entries.add(ModBlocks.CALCITE_FENCE_GATE);
                        entries.add(ModBlocks.CALCITE_WALL);
                        entries.add(ModBlocks.TUFF_FENCE);
                        entries.add(ModBlocks.TUFF_FENCE_GATE);
                        entries.add(ModBlocks.TUFF_WALL);
                        entries.add(ModBlocks.DRIPSTONE_BLOCK_FENCE);
                        entries.add(ModBlocks.DRIPSTONE_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DRIPSTONE_BLOCK_WALL);
                        entries.add(ModBlocks.PRISMARINE_FENCE);
                        entries.add(ModBlocks.PRISMARINE_FENCE_GATE);
                        entries.add(ModBlocks.PRISMARINE_WALL);

                        entries.add(ModBlocks.OBSIDIAN_FENCE);
                        entries.add(ModBlocks.OBSIDIAN_FENCE_GATE);
                        entries.add(ModBlocks.OBSIDIAN_WALL);
                        entries.add(ModBlocks.CRYING_OBSIDIAN_FENCE);
                        entries.add(ModBlocks.CRYING_OBSIDIAN_FENCE_GATE);
                        entries.add(ModBlocks.CRYING_OBSIDIAN_WALL);
                        entries.add(ModBlocks.NETHERRACK_FENCE);
                        entries.add(ModBlocks.NETHERRACK_FENCE_GATE);
                        entries.add(ModBlocks.NETHERRACK_WALL);
                        entries.add(ModBlocks.SOUL_SAND_FENCE);
                        entries.add(ModBlocks.SOUL_SAND_FENCE_GATE);
                        entries.add(ModBlocks.SOUL_SAND_WALL);
                        entries.add(ModBlocks.SOUL_SOIL_FENCE);
                        entries.add(ModBlocks.SOUL_SOIL_FENCE_GATE);
                        entries.add(ModBlocks.SOUL_SOIL_WALL);

                        entries.add(ModBlocks.SMOOTH_BASALT_FENCE);
                        entries.add(ModBlocks.SMOOTH_BASALT_FENCE_GATE);
                        entries.add(ModBlocks.SMOOTH_BASALT_WALL);
                        entries.add(ModBlocks.END_STONE_FENCE);
                        entries.add(ModBlocks.END_STONE_FENCE_GATE);
                        entries.add(ModBlocks.END_STONE_WALL);


                        entries.add(ModBlocks.MUSHROOM_STEM_FENCE);
                        entries.add(ModBlocks.MUSHROOM_STEM_FENCE_GATE);
                        entries.add(ModBlocks.MUSHROOM_STEM_WALL);
                        entries.add(ModBlocks.CRIMSON_STEM_FENCE);
                        entries.add(ModBlocks.CRIMSON_STEM_FENCE_GATE);
                        entries.add(ModBlocks.CRIMSON_STEM_WALL);
                        entries.add(ModBlocks.WARPED_STEM_FENCE);
                        entries.add(ModBlocks.WARPED_STEM_FENCE_GATE);
                        entries.add(ModBlocks.WARPED_STEM_WALL);
                        entries.add(ModBlocks.BROWN_MUSHROOM_BLOCK_FENCE);
                        entries.add(ModBlocks.BROWN_MUSHROOM_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.BROWN_MUSHROOM_BLOCK_WALL);
                        entries.add(ModBlocks.RED_MUSHROOM_BLOCK_FENCE);
                        entries.add(ModBlocks.RED_MUSHROOM_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.RED_MUSHROOM_BLOCK_WALL);
                        entries.add(ModBlocks.NETHER_WART_BLOCK_FENCE);
                        entries.add(ModBlocks.NETHER_WART_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.NETHER_WART_BLOCK_WALL);
                        entries.add(ModBlocks.WARPED_WART_BLOCK_FENCE);
                        entries.add(ModBlocks.WARPED_WART_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.WARPED_WART_BLOCK_WALL);

                        entries.add(ModBlocks.TUBE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.TUBE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.TUBE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.BRAIN_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.BRAIN_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.BRAIN_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.BUBBLE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.BUBBLE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.BUBBLE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.FIRE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.FIRE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.FIRE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.HORN_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.HORN_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.HORN_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.SPONGE_FENCE);
                        entries.add(ModBlocks.SPONGE_FENCE_GATE);
                        entries.add(ModBlocks.SPONGE_WALL);
                        entries.add(ModBlocks.WET_SPONGE_FENCE);
                        entries.add(ModBlocks.WET_SPONGE_FENCE_GATE);
                        entries.add(ModBlocks.WET_SPONGE_WALL);


                        entries.add(ModBlocks.SLIME_BLOCK_FENCE);
                        entries.add(ModBlocks.SLIME_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.SLIME_BLOCK_WALL);


                        entries.add(ModBlocks.SCULK_FENCE);
                        entries.add(ModBlocks.SCULK_FENCE_GATE);
                        entries.add(ModBlocks.SCULK_WALL);
                        entries.add(ModBlocks.BEDROCK_FENCE);
                        entries.add(ModBlocks.BEDROCK_FENCE_GATE);
                        entries.add(ModBlocks.BEDROCK_WALL);
                        entries.add(ModBlocks.GLOWSTONE_FENCE);
                        entries.add(ModBlocks.GLOWSTONE_FENCE_GATE);
                        entries.add(ModBlocks.GLOWSTONE_WALL);


                        entries.add(ModBlocks.BAMBOO_PLANKS_FENCE);
                        entries.add(ModBlocks.BAMBOO_PLANKS_FENCE_GATE);
                        entries.add(ModBlocks.BAMBOO_PLANKS_WALL);

                        entries.add(ModBlocks.BAMBOO_MOSAIC_FENCE);
                        entries.add(ModBlocks.BAMBOO_MOSAIC_FENCE_GATE);
                        entries.add(ModBlocks.BAMBOO_MOSAIC_WALL);
                        entries.add(ModBlocks.REDSTONE_BLOCK_FENCE);
                        entries.add(ModBlocks.REDSTONE_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.REDSTONE_BLOCK_WALL);
                        entries.add(ModBlocks.EMERALD_BLOCK_FENCE);
                        entries.add(ModBlocks.EMERALD_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.EMERALD_BLOCK_WALL);
                        entries.add(ModBlocks.DIAMOND_BLOCK_FENCE);
                        entries.add(ModBlocks.DIAMOND_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DIAMOND_BLOCK_WALL);
                        entries.add(ModBlocks.NETHERITE_BLOCK_FENCE);
                        entries.add(ModBlocks.NETHERITE_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.NETHERITE_BLOCK_WALL);
                        entries.add(ModBlocks.LAPIS_BLOCK_FENCE);
                        entries.add(ModBlocks.LAPIS_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.LAPIS_BLOCK_WALL);
                        entries.add(ModBlocks.GOLD_BLOCK_FENCE);
                        entries.add(ModBlocks.GOLD_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.GOLD_BLOCK_WALL);

                        entries.add(ModBlocks.AMETHYST_BLOCK_FENCE);
                        entries.add(ModBlocks.AMETHYST_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.AMETHYST_BLOCK_WALL);
                        entries.add(ModBlocks.DEAD_TUBE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.DEAD_TUBE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DEAD_TUBE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.DEAD_BRAIN_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.DEAD_BRAIN_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DEAD_BRAIN_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.DEAD_BUBBLE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.DEAD_BUBBLE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DEAD_BUBBLE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.DEAD_FIRE_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.DEAD_FIRE_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DEAD_FIRE_CORAL_BLOCK_WALL);
                        entries.add(ModBlocks.DEAD_HORN_CORAL_BLOCK_FENCE);
                        entries.add(ModBlocks.DEAD_HORN_CORAL_BLOCK_FENCE_GATE);
                        entries.add(ModBlocks.DEAD_HORN_CORAL_BLOCK_WALL);








                    }).build());
    public  static  void registerItemGroups() {
        Wallsnstuff.LOGGER.info("registering item group for wallsnstuff mod");
    }
}
